### ISSUE TITLE
Module name

### ISSUE THREAD

**Issue by anjohnson** [epics-modules/script#1]
Hi Keenan,

There are many scripting languages, and Lua is not the most well-known one (although it does seem to be a good fit for EPICS). Using just the word "script" for the name of this module instead of something more specific is IMHO a bad idea. Note that Jeff Hill is also looking to integrate Lua into EPICS, including using it as an alternative to the iocsh (see his slides from the SNS EPICS meeting for some details). If you haven't talked to him about your plans yet I suggest you try to find out whether your two approaches are likely to be compatible — I would much prefer that you two work together on this than reinvent each other's wheels.
- Andrew

**Comment by keenanlang** [comment]
> Note that Jeff Hill is also looking to integrate Lua into EPICS, including using it as an alternative to the iocsh (see his slides from the SNS EPICS meeting for some details). If you haven't talked to him about your plans yet I suggest you try to find out whether your two approaches are likely to be compatible — I would much prefer that you two work together on this than reinvent each other's wheels.

I have already sent him an email stating those exact things. I asked if there was a possibility to look over his code to eliminate duplicate effort, and as well, I gave him a link to this repository and asked for any comments and suggestions. I received only a quick reply stating that he wasn't quite comfortable making his code public because he is still constantly working on it, with no comment on anything else.

**Comment by keenanlang** [comment]
Anyone with owner privileges mind switching the repository name to "lua"?

**Comment by anjohnson** [comment]
Renamed as requested.
