### ISSUE TITLE
Replace shell.loadRegistered() with a new hook routine?

### ISSUE THREAD

**Issue by anjohnson** [epics-modules/script#10]
Suggestion: We could add a couple of hook pointers to the iocsh registration code in Base that would allow the lua bindings to get called whenever something registers a new command or variable with iocsh. That way the user wouldn't need to call `shell.loadRegistered()` at all, the registration becomes automatic. If you also add a macro to the iocsh.h header you can then use `ifdef` to detect whether the hook is available at compile-time without having to check Base version numbers. I would accept this into the Base-3.15 branch.

I suggest something similar to the `dbLoadRecordsHook` in dbAccess.c, which IIRC was added for the caPutRecorder module. Your hook routines would be responsible for passing the call onto any other hook routine that they find in the hook pointer at the time they insert themselves.

**Comment by keenanlang** [comment]
shell.loadRegistered() isn't for functions/variables registered with the ioc shell, the iocsh library doesn't need to know anything about the functions that are being registered, the ioc shell already has all that information. When a function is called by iocsh.<function name>, the code just looks up the name in the registrar and invokes it.

loadRegistered is for lua libraries and functions that use the epics dbd system to register themselves with lua. Unlike the ioc shell, there can be more than one instance of lua in an IOC. The lua shell will only ever have one, but every luascript record, lua dtyp, scriptMotor, etc. has their own lua_State holding independent environments. For each of those, whatever libraries are registered need to be loaded. For all the examples listed, the creation of the lua_State will happen after the IOC's DBD file is loaded, so all the libraries built into the IOC will be loaded on creation.

However, if you are using the lua shell as the primary shell, then when the IOC is started, the only libraries that are known about are the base libraries from lua itself (os, math, etc). Other libraries don't get registered until registerRecordDeviceDriver is called. The issue I had was that the library registration code needed to be separate from the lua shell state because it applied to any lua_State created by the IOC and because of circular dependency issues. But your suggest makes me realize that I just need to create a hook routine in luaEpics.cpp that triggers on new libraries/functions and have the shell register to pick up on those events.

**Comment by anjohnson** [comment]
Okay, so my idea was good but the hook belongs in your code, not in Base. Glad it's still useful then!

**Comment by keenanlang** [comment]
Fixed with 1518960
